application: fortune-teller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: templates/css
- url: /scripts
  static_dir: templates/scripts
- url: /images
  static_dir: templates/images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
